import { MathSymbolItem } from '../../types/math.js';

export const IRAQI_MATH_SYMBOLS: MathSymbolItem[] = [
  // 1. Basic Math (أساسيات)
  { id: 'frac', label: 'a/b', latex: '\\frac{a}{b}', category: 'basic', ariaLabel: 'كسر اعتيادي' },
  { id: 'sqrt', label: '√x', latex: '\\sqrt{x}', category: 'basic', ariaLabel: 'جذر تربيعي' },
  { id: 'sqrt_empty', label: '√{}', latex: '\\sqrt{}', category: 'basic', ariaLabel: 'جذر فارغ' },
  { id: 'nroot', label: 'ⁿ√x', latex: '\\sqrt[n]{x}', category: 'basic', ariaLabel: 'جذر نوني' },
  { id: 'pow2', label: 'x²', latex: 'x^2', category: 'basic', ariaLabel: 'مربع القيمة' },
  { id: 'powN', label: 'xⁿ', latex: 'x^{n}', category: 'basic', ariaLabel: 'قوة نونية' },
  { id: 'subN', label: 'xₙ', latex: 'x_{n}', category: 'basic', ariaLabel: 'دليل سفلي' },
  { id: 'pm', label: '±', latex: '\\pm', category: 'basic', ariaLabel: 'زائد أو ناقص' },
  { id: 'times', label: '×', latex: '\\times', category: 'basic', ariaLabel: 'ضرب' },
  { id: 'div', label: '÷', latex: '\\div', category: 'basic', ariaLabel: 'قسمة' },
  { id: 'neq', label: '≠', latex: '\\ne', category: 'basic', ariaLabel: 'لا يساوي' },
  { id: 'approx', label: '≈', latex: '\\approx', category: 'basic', ariaLabel: 'تقريباً' },
  { id: 'le', label: '≤', latex: '\\le', category: 'basic', ariaLabel: 'أصغر أو يساوي' },
  { id: 'ge', label: '≥', latex: '\\ge', category: 'basic', ariaLabel: 'أكبر أو يساوي' },
  { id: 'infty', label: '∞', latex: '\\infty', category: 'basic', ariaLabel: 'ما لا نهاية' },

  // 2. Advanced / Iraqi Curriculum Math (رياضيات عليا)
  { id: 'int', label: '∫', latex: '\\int', category: 'advanced', ariaLabel: 'تكامل غير محدد' },
  { id: 'defint', label: '∫ₐᵇ', latex: '\\int_{a}^{b}', category: 'advanced', ariaLabel: 'تكامل محدد' },
  { id: 'sum', label: '∑', latex: '\\sum', category: 'advanced', ariaLabel: 'مجموع' },
  { id: 'lim', label: 'lim', latex: '\\lim_{x \\to 0}', category: 'advanced', ariaLabel: 'غاية دالة' },
  { id: 'pi', label: 'π', latex: '\\pi', category: 'advanced', ariaLabel: 'النسبة الثابتة باي' },
  { id: 'theta', label: 'θ', latex: '\\theta', category: 'advanced', ariaLabel: 'الزاوية ثيتا' },
  { id: 'delta', label: 'Δ', latex: '\\Delta', category: 'advanced', ariaLabel: 'دلتا أو التغير' },
  { id: 'alpha', label: 'α', latex: '\\alpha', category: 'advanced', ariaLabel: 'ألفا' },
  { id: 'beta', label: 'β', latex: '\\beta', category: 'advanced', ariaLabel: 'بيتا' },
  { id: 'lambda', label: 'λ', latex: '\\lambda', category: 'advanced', ariaLabel: 'لامدا' },
  { id: 'sin', label: 'sin', latex: '\\sin(x)', category: 'advanced', ariaLabel: 'جيب' },
  { id: 'cos', label: 'cos', latex: '\\cos(x)', category: 'advanced', ariaLabel: 'جيب تمام' },
  { id: 'tan', label: 'tan', latex: '\\tan(x)', category: 'advanced', ariaLabel: 'ظل' },
  { id: 'ln', label: 'ln', latex: '\\ln(x)', category: 'advanced', ariaLabel: 'لوغاريتم طبيعي' },
  { id: 'matrix', label: '[..]', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', category: 'advanced', ariaLabel: 'مصفوفة' },

  // 3. Chemistry (كيمياء ومعادلات)
  { id: 'arrow', label: '→', latex: '->', category: 'chemistry', ariaLabel: 'سهم تفاعل' },
  { id: 'equil', label: '⇌', latex: '<=>', category: 'chemistry', ariaLabel: 'تفاعل انعكاسي متزن' },
  { id: 'heat_arrow', label: '→[Δ]', latex: '->[\\Delta]', category: 'chemistry', ariaLabel: 'سهم تفاعل بالحرارة' },
  { id: 'gas', label: '↑', latex: '^', category: 'chemistry', ariaLabel: 'تصاعد غاز' },
  { id: 'precip', label: '↓', latex: 'v', category: 'chemistry', ariaLabel: 'راسب' },
  { id: 'state_aq', label: '(aq)', latex: '(aq)', category: 'chemistry', ariaLabel: 'محلول مائي' },
  { id: 'state_s', label: '(s)', latex: '(s)', category: 'chemistry', ariaLabel: 'صلب' },
  { id: 'state_l', label: '(l)', latex: '(l)', category: 'chemistry', ariaLabel: 'سائل' },
  { id: 'state_g', label: '(g)', latex: '(g)', category: 'chemistry', ariaLabel: 'غاز' },
  { id: 'h2o', label: 'H₂O', latex: 'H2O', category: 'chemistry', ariaLabel: 'ماء' },
  { id: 'co2', label: 'CO₂', latex: 'CO2', category: 'chemistry', ariaLabel: 'ثاني أكسيد الكربون' },
  { id: 'caco3', label: 'CaCO₃', latex: 'CaCO3', category: 'chemistry', ariaLabel: 'كربونات الكالسيوم' },
  { id: 'hydrate', label: '·nH₂O', latex: '* 5H2O', category: 'chemistry', ariaLabel: 'ماء التبلور' },
  { id: 'isotope', label: 'ᴬ_Z X', latex: '^{227}_{90}Th+', category: 'chemistry', ariaLabel: 'نظير مشع وشحنة' },
  { id: 'ion_h', label: 'H⁺', latex: 'H+', category: 'chemistry', ariaLabel: 'أيون هيدروجين' },
  { id: 'ion_oh', label: 'OH⁻', latex: 'OH-', category: 'chemistry', ariaLabel: 'أيون هيدروكسيد' },

  // 4. Symbols & Brackets (رموز وأقواس)
  { id: 'paren', label: '( )', latex: '(\\dots)', category: 'symbols', ariaLabel: 'قوسان دائريان' },
  { id: 'bracket', label: '[ ]', latex: '[\\dots]', category: 'symbols', ariaLabel: 'قوسان معقوفان' },
  { id: 'brace', label: '{ }', latex: '\\{\\dots\\}', category: 'symbols', ariaLabel: 'قوسان مجدولان' },
  { id: 'abs', label: '|x|', latex: '|x|', category: 'symbols', ariaLabel: 'قيمة مطلقة' },
  { id: 'deg', label: '°', latex: '^\\circ', category: 'symbols', ariaLabel: 'درجة' },
  { id: 'bullet', label: '•', latex: '\\cdot', category: 'symbols', ariaLabel: 'نقطة ضرب' },
  { id: 'right_arr', label: '⇒', latex: '\\Rightarrow', category: 'symbols', ariaLabel: 'يؤدي إلى' },
  { id: 'equiv', label: '≡', latex: '\\equiv', category: 'symbols', ariaLabel: 'يتطابق مع' },
];
